### ISSUE TITLE
Dec Arc model ignores min altitude 

### ISSUE THREAD

**Issue by Linwood-F** [daleghent/nina-plugins#4]
On the plugin page (version 0.5.0.0) I have the altitude limit set to on and a minimum set to 30 degrees. 

When the program runs, in APPM on the measurement points page, the "min altitude" shows 30 (not sure if from the program or last run) but the min altitude box is not checked, so it fills in points down to the horizon (use horizon is also checked, but I also tried it unchecked). 

Stopping APPM and checking it of course works. 

I am not using "do full arcs"  though I do not think that should matter but have not tried.

**Comment by daleghent** [comment]
Thanks, I'll check this out the next chance I get. I presume you're running the latest APCC version?

**Comment by Linwood-F** [comment]
I think so, he sometimes puts new versions in other places, but I'm on 1.9.4.3.

I also still get 2 arcs when i ask for 3, but since I do not think you see that I wonder if I'm hitting a rounding error somewhere.  Let me know if you want details on that again.  I decided 2 was plenty though.  :)

**Comment by daleghent** [comment]
Linwood, can you try this plugin DLL? Just drop it in over your existing one. It probably won't fix the 2/3 arc fence post issue, but it will hopefully address the settings issue.
[DaleGhent.NINA.AstroPhysicsTools.zip](https://github.com/daleghent/nina-plugins/files/8751110/DaleGhent.NINA.AstroPhysicsTools.zip)

**Comment by Linwood-F** [comment]
Clouds continually... I'll try to get it set up inside enough to fire it off, I think I just need the mount connected but I may need a camera for APPM to start.  Hopefully tomorrow.  Thank you.

**Comment by daleghent** [comment]
Connect a simulated camera and tick the "Manual mode" and "Keep APPM Open" options in the Create Dec Arc instruction. That'll open APPM with the generated settings but not make it connect to anything or run the model. You can then look at the settings on the Measurement tab and open the "Show points" window in APPM without much fuss.

**Comment by Linwood-F** [comment]
Sorry for the delay in trying it; I did, and it works fine with respect to the minimum altitude.  Thank you.
